services:
  web:
    container_name: niltonpimentel_django
    image: niltonpimentel/niltonpimentel:latest
    env_file: .env
    expose:
      - "8900"
    depends_on:
      - postgres
    volumes:
      - /etc/localtime/:/etc/localtime
    command: gunicorn nilton_pimentel.wsgi:application -w 2 -b :8900 --threads 1 --timeout 80
    networks:
      - niltonpimentel-nt

  postgres:
    container_name: niltonpimentel_postgres
    image: postgres:latest
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5434:5432
    networks:
      - niltonpimentel-nt

networks:
  niltonpimentel-nt:
    external:
      name: niltonpimentel-nt
