name: Build Docker Container & Push To Docker Hub

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test_django_job:
    uses: niltonpimentel02/nilton_pimentel/.github/workflows/test.yml@main

  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: test_django_job
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: niltonpimentel/niltonpimentel:latest

  deploy-server:
    name: Build Server Main
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: checkout
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_MAIN_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_MAIN_PRIVATE_KEY }}
          port: ${{ secrets.HOST_PORT }}
          shell: 'script -q -e -c "bash {0}"'
          script: |
            cd opt/nilton_pimentel
            git pull
            docker pull niltonpimentel/niltonpimentel:latest
            docker compose up -d --force-recreate web
            cd nginx
            docker compose up -d --force-recreate
