name: Build Docker Container & Push To Docker Hub

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]

env:
  SHA: ${{ github.event.pull_request.head.sha || github.sha }}

jobs:
  push-docker-image-to-docker-hub:
    name: Push Docker Image To Docker Hub
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
      security-events: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v7
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Log In To Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build For CVE Analysis
        uses: docker/build-push-action@v7
        with:
          context: .
          push: false
          load: true
          tags: |
            niltonpimentel/niltonpimentel:${{ env.SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Analyze For Critical And High CVEs
        uses: docker/scout-action@v1
        with:
          command: cves
          image: niltonpimentel/niltonpimentel:${{ env.SHA }}
          only-severities: critical,high
          only-fixed: true
          summary: true
          exit-code: true
      - name: Analyze For All CVEs
        uses: docker/scout-action@v1
        with:
          command: cves
          image: niltonpimentel/niltonpimentel:${{ env.SHA }}
          summary: true
      - name: Push To Docker Hub
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            niltonpimentel/niltonpimentel:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  create-env-file:
    name: Create Env File
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: Checkout
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_PRIVATE_KEY }}
          script: |
            cd /opt/projects/nilton_pimentel
            # sudo rm .env
            # cat << EOF >> .env
            sudo tee .env > /dev/null << 'EOF'
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            DEBUG=${{ secrets.DEBUG }}
            ALLOWED_HOSTS=${{ vars.ALLOWED_HOSTS }}

            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}

            CLOUDFLARE_R2_BUCKET=${{ secrets.CLOUDFLARE_R2_BUCKET}}
            CLOUDFLARE_R2_ACCESS_KEY=${{ secrets.CLOUDFLARE_R2_ACCESS_KEY}}
            CLOUDFLARE_R2_SECRET_KEY=${{ secrets.CLOUDFLARE_R2_SECRET_KEY}}
            CLOUDFLARE_R2_BUCKET_ENDPOINT=${{ secrets.CLOUDFLARE_R2_BUCKET_ENDPOINT}}

            EMAIL_BACKEND=${{ secrets.EMAIL_BACKEND }}
            EMAIL_HOST=${{ secrets.EMAIL_HOST }}
            EMAIL_PORT=${{ secrets.EMAIL_PORT }}
            EMAIL_USER=${{ secrets.EMAIL_USER }}
            EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}

            SENTRY_DSN=${{ secrets.SENTRY_DSN }}
            EOF

            sudo chmod 600 .env

  copy-config-files:
    name: Copy Config Files
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: Checkout
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_PRIVATE_KEY }}
          source: "config/*"
          target: "/opt/projects/nilton_pimentel"

  restart-docker-containers:
    name: Restart Docker Containers
    runs-on: ubuntu-24.04
    needs: [push-docker-image-to-docker-hub, create-env-file, copy-config-files]
    steps:
      - uses: actions/checkout@v7
      - name: Checkout
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_PRIVATE_KEY }}
          script: |
            cd /opt/projects/nilton_pimentel
            docker pull niltonpimentel/niltonpimentel:latest
            cp config/docker-compose.yml docker-compose.yml
            cp -r config/traefik/* traefik/
            docker compose up -d --force-recreate traefik app

  apply-django-migrations:
    name: Apply Django Migrations
    runs-on: ubuntu-24.04
    needs: restart-docker-containers
    steps:
      - uses: actions/checkout@v7
      - name: Checkout
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_PRIVATE_KEY }}
          script: |
            cd /opt/projects/nilton_pimentel
            docker exec --tty app python manage.py migrate --noinput

  run-django-collectstatic:
    name: Run Django Collect Static
    runs-on: ubuntu-24.04
    needs: restart-docker-containers
    steps:
      - uses: actions/checkout@v7
      - name: Checkout
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_PRIVATE_KEY }}
          script: |
            cd /opt/projects/nilton_pimentel
            docker exec --tty app python manage.py collectstatic --no-input
