name: Build Docker Container & Push To Docker Hub

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: [main]
#  push:
#    branches: [main]

jobs:
  test_django_job:
    name: Test Django
#    uses: niltonpimentel02/nilton_pimentel/.github/workflows/test.yml@main
    uses: niltonpimentel02/nilton_pimentel/.github/workflows/test.yml@feature/sc-9130

  build:
    name: Push Docker Image To Docker Hub
    runs-on: ubuntu-latest
    needs: test_django_job
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log In To Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push To Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            niltonpimentel/niltonpimentel:latest

  copy-config-files:
    name: Copy Config Files
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Checkout
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.HOST_USERNAME }}
        key: ${{ secrets.HOST_PRIVATE_KEY }}
        source: 'droplets_config/*'
        target: '/opt/nilton_pimentel'
