name: Build Docker Container & Push To Docker Hub

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test_django_job:
    name: Test Django
    uses: niltonpimentel02/nilton_pimentel/.github/workflows/test.yml@main

  build:
    name: Push Docker Image To Docker Hub
    runs-on: ubuntu-latest
    needs: test_django_job
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log In To Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push To Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            niltonpimentel/niltonpimentel:latest

  copy-config-files:
    name: Copy Config Files
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Checkout
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.HOST_USERNAME }}
        key: ${{ secrets.HOST_PRIVATE_KEY }}
        source: 'config/*'
        target: '/opt/projects/nilton_pimentel'

  deploy-server:
    name: Deploy Server
    runs-on: ubuntu-latest
    needs: copy-config-files
    steps:
      - uses: actions/checkout@v3
      - name: Checkout
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_PRIVATE_KEY }}
          script: |
            cd /opt/projects/nilton_pimentel
            rm .env
            cat << EOF >> .env
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            DEBUG=${{ secrets.DEBUG }}
            ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            EMAIL_BACKEND=${{ secrets.EMAIL_BACKEND }}
            EMAIL_HOST=${{ secrets.EMAIL_HOST }}
            EMAIL_PORT=${{ secrets.EMAIL_PORT }}
            EMAIL_USE_TLS=${{ secrets.EMAIL_USE_TLS }}
            EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}
            EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}
            EOF

  restart-docker-containers:
    name: Restart Docker Containers
    runs-on: ubuntu-latest
    needs: deploy-server
    steps:
      - uses: actions/checkout@v3
      - name: Checkout
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_PRIVATE_KEY }}
          script: |
            cd /opt/projects/nilton_pimentel
            docker pull niltonpimentel/niltonpimentel:latest
            cp config/docker-compose.yml docker-compose.yml
            cp config/nginx.conf nginx_config/nginx.conf
            docker compose up -d --force-recreate nginx app

  apply-django-data:
    name: Apply Django Data
    runs-on: ubuntu-latest
    needs: restart-docker-containers
    steps:
      - uses: actions/checkout@v3
      - name: Checkout
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_PRIVATE_KEY }}
          script: |
            cd /opt/projects/nilton_pimentel
            docker exec --tty app /opt/.venv/bin/python manage.py migrate --noinput
            docker exec --tty app /opt/.venv/bin/python manage.py collectstatic --no-input
