name: Django CI & Postgres Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  django_test:
    name: Test Django
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: .
    env:
#      DEBUG: False
      SECRET_KEY: test-key-not-good-maybe-make-one-better
      ALLOWED_HOSTS: 127.0.0.1

      DB_NAME: dockerdc
      DB_USER: myuser
      DB_PASSWORD: mysecretpassword
      DB_HOST: localhost
      DB_PORT: 5432
      DB_TEST: test_mydb

      CLOUDFLARE_R2_BUCKET: bucket
#      CLOUDFLARE_R2_ACCESS_KEY: access-key
#      CLOUDFLARE_R2_SECRET_KEY: secret-key
#      CLOUDFLARE_R2_BUCKET_ENDPOINT: endpoint

      EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
      EMAIL_HOST: smtp.server.com
      EMAIL_PORT: 587
      EMAIL_USER: myuser
      EMAIL_PASSWORD: mysecretpassword
    services:
      postgres_main:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
        ports:
          - 5434:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.0]
    steps:
      - uses: actions/checkout@v4
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Pytest
        run: |
          pytest
